# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FzL6VMzkhFCsBmsOq1jAECIZ_QHo-kuF
"""

# =========================================
# 1. Install library
# =========================================
!pip install rispy

# =========================================
# 2. Import library
# =========================================
import rispy
import pandas as pd

# =========================================
# 3. Path file RIS
# =========================================
file_path = "/content/sample_data/scopus_export_Mar 18-2026_e8021411-1195-4ecb-813a-d60e9e87551e.ris"

# =========================================
# 4. Parse RIS
# =========================================
with open(file_path, 'r', encoding='utf-8') as file:
    entries = rispy.load(file)

df = pd.DataFrame(entries)

print("Jumlah data:", len(df))
print("Jumlah kolom:", len(df.columns))
print("Daftar kolom:", df.columns.tolist())

# =========================================
# 5. Cleaning (flatten semua list → string)
# =========================================
def clean_list(x):
    if isinstance(x, list):
        return '; '.join(map(str, x))
    return x

df = df.applymap(clean_list)

# =========================================
# 6. Export ke Excel (SEMUA kolom dipertahankan)
# =========================================
output_path = "/content/scopus_full.xlsx"
df.to_excel(output_path, index=False)

print("File berhasil disimpan di:", output_path)

# ============================================================
# FULL CODE: BERTopic + Time Series + Hot/Cold Topics
# ============================================================

# ── INSTALL ─────────────────────────────────────────────────
!pip install bertopic sentence-transformers umap-learn hdbscan gensim -q

# ── IMPORTS ─────────────────────────────────────────────────
import pandas as pd
import numpy as np
import warnings
import re
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from scipy import stats

import torch
from sentence_transformers import SentenceTransformer
from bertopic import BERTopic
from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer
from gensim.models.coherencemodel import CoherenceModel
from gensim.corpora.dictionary import Dictionary

warnings.filterwarnings('ignore')

# ════════════════════════════════════════════════════════════
# 1. LOAD DATA
# ════════════════════════════════════════════════════════════
df = pd.read_excel('/content/sample_data/scopus_full_tahap 2.xlsx')
print(f"Shape awal   : {df.shape}")
print(f"Kolom        : {df.columns.tolist()}\n")

# ════════════════════════════════════════════════════════════
# 2. PREPROCESSING — GABUNG TITLE + ABSTRACT
# ════════════════════════════════════════════════════════════
def combine_text(row):
    title    = str(row['title'])    if pd.notna(row['title'])    else ''
    abstract = str(row['abstract']) if pd.notna(row['abstract']) else ''
    return (title + ' ' + abstract).strip() or None

df['text'] = df.apply(combine_text, axis=1)
df['year'] = pd.to_numeric(df['year'], errors='coerce')

df_clean = df[
    df['text'].notna() &
    (df['text'].str.len() > 20) &
    df['year'].notna()
].reset_index(drop=True)

docs       = df_clean['text'].tolist()
timestamps = df_clean['year'].astype(int).tolist()

print(f"Dokumen valid : {len(docs)}")
print(f"Rentang tahun : {min(timestamps)} – {max(timestamps)}\n")

# ════════════════════════════════════════════════════════════
# 3. EMBEDDING — all-mpnet-base-v2
# ════════════════════════════════════════════════════════════
print("Loading model: all-mpnet-base-v2 ...")
embedding_model = SentenceTransformer('all-mpnet-base-v2')

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Device        : {device}")

print("Encoding dokumen (beberapa menit)...")
embeddings = embedding_model.encode(
    docs,
    show_progress_bar=True,
    batch_size=32,
    device=device
)
print(f"Embedding shape: {embeddings.shape}\n")

# ════════════════════════════════════════════════════════════
# 4. PERSIAPAN COHERENCE
# ════════════════════════════════════════════════════════════
def tokenize(text):
    text   = text.lower()
    text   = re.sub(r'[^a-z\s]', ' ', text)
    tokens = [t for t in text.split() if len(t) > 2]
    return tokens

tokenized_docs = [tokenize(d) for d in docs]
gensim_dict    = Dictionary(tokenized_docs)

def compute_coherence(topic_model, tokenized, dictionary):
    topic_words = []
    for _, row in topic_model.get_topic_info().iterrows():
        tid = row['Topic']
        if tid == -1:
            continue
        words = [w for w, _ in topic_model.get_topic(tid)
                 if w in dictionary.token2id]
        if words:
            topic_words.append(words)
    if not topic_words:
        return 0.0
    cm = CoherenceModel(
        topics=topic_words,
        texts=tokenized,
        dictionary=dictionary,
        coherence='c_v'
    )
    return cm.get_coherence()

# ════════════════════════════════════════════════════════════
# 5. EKSPERIMENTASI min_cluster_size
# ════════════════════════════════════════════════════════════
umap_model = UMAP(
    n_neighbors=15,
    n_components=5,
    min_dist=0.0,
    metric='cosine',
    random_state=42
)

vectorizer_model = CountVectorizer(
    stop_words='english',
    min_df=3,
    ngram_range=(1, 2)
)

min_cluster_sizes = [5, 10, 15, 20, 25]
results = []
models  = {}

print("=" * 65)
print(f"{'min_cluster_size':>18} | {'n_topics':>8} | {'coherence_cv':>13} | {'outlier_%':>10}")
print("=" * 65)

for mcs in min_cluster_sizes:
    hdbscan_model = HDBSCAN(
        min_cluster_size=mcs,
        min_samples=1,
        metric='euclidean',
        cluster_selection_method='eom',
        prediction_data=True
    )

    topic_model = BERTopic(
        umap_model=umap_model,
        hdbscan_model=hdbscan_model,
        vectorizer_model=vectorizer_model,
        embedding_model=embedding_model,
        top_n_words=10,
        verbose=False
    )

    topics, probs = topic_model.fit_transform(docs, embeddings)

    n_topics    = len(set(topics)) - (1 if -1 in topics else 0)
    outlier_pct = topics.count(-1) / len(topics) * 100
    coh         = compute_coherence(topic_model, tokenized_docs, gensim_dict)

    models[mcs] = {
        'model'      : topic_model,
        'topics'     : topics,
        'probs'      : probs,
        'n_topics'   : n_topics,
        'coherence'  : coh,
        'outlier_pct': outlier_pct
    }
    results.append({
        'min_cluster_size': mcs,
        'n_topics'        : n_topics,
        'coherence_cv'    : round(coh, 4),
        'outlier_pct'     : round(outlier_pct, 2)
    })

    print(f"{mcs:>18} | {n_topics:>8} | {coh:>13.4f} | {outlier_pct:>9.2f}%")

print("=" * 65)

# ════════════════════════════════════════════════════════════
# 6. PILIH MODEL TERBAIK
# ════════════════════════════════════════════════════════════
results_df = pd.DataFrame(results)
print(f"\n📊 Tabel Eksperimentasi:\n{results_df.to_string(index=False)}\n")

best_row = results_df.loc[results_df['coherence_cv'].idxmax()]
best_mcs = int(best_row['min_cluster_size'])

print(f"✅ Model Terbaik  : min_cluster_size = {best_mcs}")
print(f"   Jumlah Topik  : {best_row['n_topics']}")
print(f"   Coherence CV  : {best_row['coherence_cv']}")
print(f"   Outlier       : {best_row['outlier_pct']}%\n")

best_model  = models[best_mcs]['model']
best_topics = models[best_mcs]['topics']
best_probs  = models[best_mcs]['probs']

# ════════════════════════════════════════════════════════════
# 7. TOPIC INFO & LABEL — 10 KATA KUNCI
# ════════════════════════════════════════════════════════════
def get_topic_label(tid, model, n=4):
    if tid == -1:
        return 'Outlier'
    words = [w for w, _ in model.get_topic(tid)]
    return '_'.join(words[:n])

def get_top10_words(tid, model):
    if tid == -1:
        return []
    return model.get_topic(tid)[:10]

topic_info   = best_model.get_topic_info()
topic_labels = {
    row['Topic']: get_topic_label(row['Topic'], best_model)
    for _, row in topic_info.iterrows()
}

# ── Cetak 10 kata kunci per topik ────────────────────────
print("=" * 80)
print("📌  10 KATA KUNCI PER TOPIK")
print("=" * 80)
for _, row in topic_info.iterrows():
    tid = row['Topic']
    if tid == -1:
        continue
    top10     = get_top10_words(tid, best_model)
    words_str = '  |  '.join([f"{w} ({s:.4f})" for w, s in top10])
    tnum      = tid + 1
    print(f"\n  Topic {tnum}  [{topic_labels[tid]}]  — count: {row['Count']}")
    print(f"  {words_str}")
print("\n" + "=" * 80 + "\n")

# ── Bar chart 10 kata kunci per topik ────────────────────
n_valid_topics = sum(1 for _, r in topic_info.iterrows() if r['Topic'] != -1)
n_cols_kw      = 3
n_rows_kw      = (n_valid_topics + n_cols_kw - 1) // n_cols_kw
colors_kw      = cm.tab20(np.linspace(0, 1, n_valid_topics))

fig_kw, axes_kw = plt.subplots(
    n_rows_kw, n_cols_kw,
    figsize=(7 * n_cols_kw, 4 * n_rows_kw)
)
axes_kw  = axes_kw.flatten()
plot_idx = 0

for _, row in topic_info.iterrows():
    tid = row['Topic']
    if tid == -1:
        continue
    top10     = get_top10_words(tid, best_model)
    kw_words  = [w for w, _ in top10]
    kw_scores = [s for _, s in top10]
    tnum      = tid + 1
    ax        = axes_kw[plot_idx]

    bars = ax.barh(kw_words[::-1], kw_scores[::-1],
                   color=colors_kw[plot_idx],
                   edgecolor='white', height=0.65)
    for bar, val in zip(bars, kw_scores[::-1]):
        ax.text(val + 0.001,
                bar.get_y() + bar.get_height() / 2,
                f'{val:.4f}', va='center', ha='left', fontsize=7)

    ax.set_title(
        f'Topic {tnum}  (n={row["Count"]})\n{topic_labels[tid][:45]}',
        fontsize=8, fontweight='bold', pad=4
    )
    ax.set_xlabel('c-TF-IDF Score', fontsize=7)
    ax.tick_params(axis='y', labelsize=8)
    ax.tick_params(axis='x', labelsize=7)
    ax.grid(True, axis='x', alpha=0.3)
    plot_idx += 1

for j in range(plot_idx, len(axes_kw)):
    axes_kw[j].set_visible(False)

plt.suptitle(
    f'10 Kata Kunci per Topik  |  mcs={best_mcs}  |  '
    f'Coherence CV={best_row["coherence_cv"]}',
    fontsize=13, fontweight='bold', y=1.01
)
plt.tight_layout()
plt.savefig('/content/sample_data/keywords_per_topic.png',
            dpi=150, bbox_inches='tight')
plt.show()
print("✅ keywords_per_topic.png tersimpan\n")

# ════════════════════════════════════════════════════════════
# 8. SIMPAN ASSIGNMENT KE df_clean
# ════════════════════════════════════════════════════════════
df_clean['topic']       = best_topics
df_clean['topic_label'] = df_clean['topic'].apply(
    lambda t: get_topic_label(t, best_model)
)
df_clean['topic_num']   = df_clean['topic'].apply(
    lambda t: t + 1 if t != -1 else -1        # nomor tampilan mulai dari 1
)
df_clean['topic_prob']  = [
    float(p.max()) if hasattr(p, '__len__') else float(p)
    for p in best_probs
]

# ════════════════════════════════════════════════════════════
# 9. TIME SERIES PER TOPIK
# ════════════════════════════════════════════════════════════
df_notoutlier = df_clean[df_clean['topic'] != -1].copy()
years_all     = sorted(df_notoutlier['year'].unique())
topic_ids     = sorted(df_notoutlier['topic'].unique())
n_topics_ts   = len(topic_ids)

ts_matrix = pd.DataFrame(0, index=years_all, columns=topic_ids)
for _, row in df_notoutlier.iterrows():
    ts_matrix.loc[row['year'], row['topic']] += 1

ts_proportion = ts_matrix.div(ts_matrix.sum(axis=1), axis=0).fillna(0)
colors_ts     = cm.tab20(np.linspace(0, 1, n_topics_ts))

# ── Grid tiap topik ───────────────────────────────────────
n_cols_ts = 3
n_rows_ts = (n_topics_ts + n_cols_ts - 1) // n_cols_ts

fig_ts, axes_ts = plt.subplots(
    n_rows_ts, n_cols_ts,
    figsize=(6 * n_cols_ts, 3.5 * n_rows_ts)
)
axes_ts = axes_ts.flatten()

for i, tid in enumerate(topic_ids):
    ax   = axes_ts[i]
    tnum = tid + 1
    y    = ts_matrix[tid].values
    x    = np.array(years_all)

    ax.fill_between(x, y, alpha=0.25, color=colors_ts[i])
    ax.plot(x, y, 'o-', color=colors_ts[i], linewidth=1.8, markersize=4)

    if len(x) > 1:
        slope, intercept, *_ = stats.linregress(x, y)
        ax.plot(x, slope * x + intercept, '--',
                color='black', linewidth=1.2, alpha=0.7)
        ax.set_title(
            f'Topic {tnum} | slope={slope:+.3f}\n{topic_labels[tid][:40]}',
            fontsize=8, pad=3
        )
    else:
        ax.set_title(
            f'Topic {tnum}\n{topic_labels[tid][:40]}',
            fontsize=8, pad=3
        )

    ax.set_xlabel('Year', fontsize=7)
    ax.set_ylabel('Count', fontsize=7)
    ax.tick_params(labelsize=7)
    ax.grid(True, alpha=0.3)

for j in range(i + 1, len(axes_ts)):
    axes_ts[j].set_visible(False)

plt.suptitle(
    f'Time Series per Topik  |  mcs={best_mcs}  |  '
    f'Coherence CV={best_row["coherence_cv"]}',
    fontsize=12, y=1.01, fontweight='bold'
)
plt.tight_layout()
plt.savefig('/content/sample_data/timeseries_per_topic.png',
            dpi=150, bbox_inches='tight')
plt.show()
print("✅ timeseries_per_topic.png tersimpan\n")

# ── Stacked area ──────────────────────────────────────────
fig_sa, ax_sa = plt.subplots(figsize=(14, 6))
bottom = np.zeros(len(years_all))

for i, tid in enumerate(topic_ids):
    tnum = tid + 1
    vals = ts_proportion[tid].values
    ax_sa.fill_between(years_all, bottom, bottom + vals,
                       alpha=0.75, color=colors_ts[i],
                       label=f'T{tnum}: {topic_labels[tid][:25]}')
    bottom += vals

ax_sa.set_xlabel('Year', fontsize=11)
ax_sa.set_ylabel('Proporsi Topik', fontsize=11)
ax_sa.set_title('Stacked Area — Proporsi Topik per Tahun',
                fontsize=13, fontweight='bold')
ax_sa.legend(loc='upper left', bbox_to_anchor=(1, 1),
             fontsize=7, ncol=1, framealpha=0.8)
ax_sa.set_xlim(min(years_all), max(years_all))
ax_sa.set_ylim(0, 1)
ax_sa.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('/content/sample_data/timeseries_stacked.png',
            dpi=150, bbox_inches='tight')
plt.show()
print("✅ timeseries_stacked.png tersimpan\n")

# ════════════════════════════════════════════════════════════
# 10. HOT & COLD TOPICS — slope > 0 = HOT, slope < 0 = COLD
# ════════════════════════════════════════════════════════════
slope_data = []
x_years    = np.array(years_all, dtype=float)

for tid in topic_ids:
    y_vals = ts_matrix[tid].values.astype(float)
    top10  = get_top10_words(tid, best_model)
    words  = [w for w, _ in top10]

    if len(x_years) > 1 and y_vals.std() > 0:
        slope, _, r_val, p_val, _ = stats.linregress(x_years, y_vals)
    else:
        slope, r_val, p_val = 0.0, 0.0, 1.0

    slope_data.append({
        'topic_id'    : tid,
        'topic_num'   : tid + 1,               # nomor tampilan mulai dari 1
        'topic_label' : topic_labels[tid],
        'top_10_words': ', '.join(words),
        'total_docs'  : int(ts_matrix[tid].sum()),
        'slope'       : round(slope,    5),
        'r_squared'   : round(r_val**2, 4),
        'p_value'     : round(p_val,    4)
    })

slope_df = (pd.DataFrame(slope_data)
              .sort_values('slope', ascending=False)
              .reset_index(drop=True))

# ── Filter hot / cold ─────────────────────────────────────
hot_topics  = (slope_df[slope_df['slope'] > 0]
               .sort_values('topic_id')        # urut topic_id ascending
               .head(5)
               .reset_index(drop=True))

cold_topics = (slope_df[slope_df['slope'] < 0]
               .sort_values('topic_id')        # urut topic_id ascending
               .head(5)
               .reset_index(drop=True))

print(f"Topik dengan slope > 0 (HOT)  : {len(slope_df[slope_df['slope'] > 0])}")
print(f"Topik dengan slope = 0 (FLAT) : {len(slope_df[slope_df['slope'] == 0])}")
print(f"Topik dengan slope < 0 (COLD) : {len(slope_df[slope_df['slope'] < 0])}\n")

# ── Print hot ─────────────────────────────────────────────
print("=" * 80)
print("🔥  HOT TOPICS  (slope > 0 → tren NAIK)")
print("=" * 80)
if hot_topics.empty:
    print("  Tidak ada topik dengan slope positif.")
else:
    for _, r in hot_topics.iterrows():
        print(f"\n  Topic {r['topic_num']:>3}  slope={r['slope']:+.5f}  "
              f"R²={r['r_squared']}  p={r['p_value']}")
        print(f"  Label     : {r['topic_label']}")
        print(f"  Top 10    : {r['top_10_words']}")
        print(f"  Total dok : {r['total_docs']}")

# ── Print cold ────────────────────────────────────────────
print("\n" + "=" * 80)
print("🧊  COLD TOPICS  (slope < 0 → tren TURUN)")
print("=" * 80)
if cold_topics.empty:
    print("  Tidak ada topik dengan slope negatif.")
else:
    for _, r in cold_topics.iterrows():
        print(f"\n  Topic {r['topic_num']:>3}  slope={r['slope']:+.5f}  "
              f"R²={r['r_squared']}  p={r['p_value']}")
        print(f"  Label     : {r['topic_label']}")
        print(f"  Top 10    : {r['top_10_words']}")
        print(f"  Total dok : {r['total_docs']}")

print("\n" + "=" * 80 + "\n")

# ── Plot Hot & Cold ───────────────────────────────────────
n_hot_plot  = len(hot_topics)
n_cold_plot = len(cold_topics)
n_cols_hc   = max(n_hot_plot, n_cold_plot, 1)

fig_hc, axes_hc = plt.subplots(2, n_cols_hc,
                                figsize=(5 * n_cols_hc, 8))
if n_cols_hc == 1:
    axes_hc = np.array(axes_hc).reshape(2, 1)

# Baris 0 → Hot (sudah diurutkan topic_id ascending)
for col in range(n_cols_hc):
    ax = axes_hc[0, col]
    if col < n_hot_plot:
        r    = hot_topics.iloc[col]
        tid  = r['topic_id']
        tnum = r['topic_num']              # nomor tampilan (tid + 1)
        x, y = x_years, ts_matrix[tid].values.astype(float)
        sv   = r['slope']
        trend = sv * x + (y.mean() - sv * x.mean())

        ax.fill_between(x, y, alpha=0.3, color='crimson')
        ax.plot(x, y, 'o-', color='crimson', linewidth=2, markersize=5)
        ax.plot(x, trend, '--', color='darkred', linewidth=1.5)
        ax.set_title(
            f'🔥 Topic {tnum}: {r["topic_label"][:28]}\nslope={sv:+.4f}',
            fontsize=8, color='crimson'
        )
        ax.set_xlabel('Year', fontsize=7)
        ax.set_ylabel('Count', fontsize=7)
        ax.tick_params(labelsize=7)
        ax.grid(True, alpha=0.3)
    else:
        ax.set_visible(False)

# Baris 1 → Cold (sudah diurutkan topic_id ascending)
for col in range(n_cols_hc):
    ax = axes_hc[1, col]
    if col < n_cold_plot:
        r    = cold_topics.iloc[col]
        tid  = r['topic_id']
        tnum = r['topic_num']              # nomor tampilan (tid + 1)
        x, y = x_years, ts_matrix[tid].values.astype(float)
        sv   = r['slope']
        trend = sv * x + (y.mean() - sv * x.mean())

        ax.fill_between(x, y, alpha=0.3, color='steelblue')
        ax.plot(x, y, 'o-', color='steelblue', linewidth=2, markersize=5)
        ax.plot(x, trend, '--', color='navy', linewidth=1.5)
        ax.set_title(
            f'🧊 Topic {tnum}: {r["topic_label"][:28]}\nslope={sv:+.4f}',
            fontsize=8, color='steelblue'
        )
        ax.set_xlabel('Year', fontsize=7)
        ax.set_ylabel('Count', fontsize=7)
        ax.tick_params(labelsize=7)
        ax.grid(True, alpha=0.3)
    else:
        ax.set_visible(False)

axes_hc[0, 0].annotate('HOT TOPICS', xy=(-0.22, 0.5),
                        xycoords='axes fraction', fontsize=12,
                        fontweight='bold', color='crimson',
                        rotation=90, va='center')
axes_hc[1, 0].annotate('COLD TOPICS', xy=(-0.22, 0.5),
                        xycoords='axes fraction', fontsize=12,
                        fontweight='bold', color='steelblue',
                        rotation=90, va='center')

plt.suptitle('Hot & Cold Topics  (🔥 slope > 0  |  🧊 slope < 0)',
             fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('/content/sample_data/hot_cold_topics.png',
            dpi=150, bbox_inches='tight')
plt.show()
print("✅ hot_cold_topics.png tersimpan\n")

# ── Slope bar chart ───────────────────────────────────────
# Urutkan berdasarkan topic_num untuk konsistensi label
slope_df_sorted = slope_df.sort_values('topic_id').reset_index(drop=True)

fig_sb, ax_sb = plt.subplots(figsize=(12, max(5, n_topics_ts * 0.5)))

bar_colors = ['crimson' if s > 0 else ('steelblue' if s < 0 else 'grey')
               for s in slope_df_sorted['slope']]
bar_labels = [f"Topic {r['topic_num']}: {r['topic_label'][:35]}"
              for _, r in slope_df_sorted.iterrows()]

bars = ax_sb.barh(bar_labels, slope_df_sorted['slope'],
                  color=bar_colors, edgecolor='white', height=0.65)
ax_sb.axvline(0, color='black', linewidth=1.5, linestyle='--')
ax_sb.set_xlabel('Slope Regresi Linear', fontsize=11)
ax_sb.set_title(
    'Slope per Topik\n(🔥 merah = slope > 0 HOT  |  🧊 biru = slope < 0 COLD  |  abu = 0)',
    fontsize=12, fontweight='bold'
)
ax_sb.tick_params(axis='y', labelsize=8)
ax_sb.grid(True, axis='x', alpha=0.3)

for bar, val in zip(bars, slope_df_sorted['slope']):
    offset = 0.0003 if val >= 0 else -0.0003
    ax_sb.text(val + offset,
               bar.get_y() + bar.get_height() / 2,
               f'{val:+.4f}',
               va='center',
               ha='left' if val >= 0 else 'right',
               fontsize=7)

plt.tight_layout()
plt.savefig('/content/sample_data/slope_barchart.png',
            dpi=150, bbox_inches='tight')
plt.show()
print("✅ slope_barchart.png tersimpan\n")

# ════════════════════════════════════════════════════════════
# 11. SIMPAN KE EXCEL
# ════════════════════════════════════════════════════════════
output_cols = [c for c in
               ['No','title','abstract','text','year',
                'topic','topic_num','topic_label','topic_prob']
               if c in df_clean.columns]

def tag_status(s):
    if s > 0: return '🔥 HOT'
    if s < 0: return '🧊 COLD'
    return '➡️ FLAT'

slope_df['status'] = slope_df['slope'].apply(tag_status)

with pd.ExcelWriter('/content/sample_data/bertopic_full_results.xlsx',
                    engine='openpyxl') as writer:

    # Sheet 1 – Eksperimentasi
    results_df.to_excel(writer, sheet_name='Eksperimentasi', index=False)

    # Sheet 2 – Dokumen + topik
    df_clean[output_cols].to_excel(
        writer, sheet_name='Dokumen_Topik', index=False)

    # Sheet 3 – Topic keywords (10 kata, kolom terpisah)
    topic_info_export = []
    for _, row in topic_info.iterrows():
        if row['Topic'] == -1:
            continue
        top10 = get_top10_words(row['Topic'], best_model)
        entry = {
            'topic_id'   : row['Topic'],
            'topic_num'  : row['Topic'] + 1,
            'topic_label': topic_labels[row['Topic']],
            'count'      : row['Count'],
        }
        for rank, (w, s) in enumerate(top10, start=1):
            entry[f'kw_{rank}']       = w
            entry[f'kw_{rank}_score'] = round(s, 5)
        topic_info_export.append(entry)

    pd.DataFrame(topic_info_export).to_excel(
        writer, sheet_name='Topic_Keywords', index=False)

    # Sheet 4 – Slope / Hot-Cold
    slope_df.to_excel(writer, sheet_name='Slope_HotCold', index=False)

    # Sheet 5 – Time series count
    ts_export = ts_matrix.reset_index().rename(columns={'index': 'year'})
    ts_export.columns = ['year'] + [f'Topic_{c+1}' for c in ts_export.columns[1:]]
    ts_export.to_excel(writer, sheet_name='TimeSeries_Count', index=False)

    # Sheet 6 – Time series proporsi
    tp_export = ts_proportion.reset_index().rename(columns={'index': 'year'})
    tp_export.columns = ['year'] + [f'Topic_{c+1}' for c in tp_export.columns[1:]]
    tp_export.to_excel(writer, sheet_name='TimeSeries_Proportion', index=False)

print("✅ bertopic_full_results.xlsx tersimpan")
print("   Sheet: Eksperimentasi | Dokumen_Topik | Topic_Keywords |")
print("          Slope_HotCold | TimeSeries_Count | TimeSeries_Proportion")
print("\n🎉 SELESAI!")

